// Code generated by tommy; DO NOT EDIT.

package sweatfile

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type SweatfileDocument struct {
	data     Sweatfile
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeSweatfile(input []byte) (*SweatfileDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &SweatfileDocument{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "system-prompt"); err == nil {
		d.data.SystemPrompt = &v
		d.consumed["system-prompt"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "system-prompt-append"); err == nil {
		d.data.SystemPromptAppend = &v
		d.consumed["system-prompt-append"] = true
	}
	if v, err := document.GetFromContainer[[]string](d.cstDoc, d.cstDoc.Root(), "git-excludes"); err == nil {
		d.data.GitSkipIndex = v
		d.consumed["git-excludes"] = true
	}
	if v, err := document.GetFromContainer[[]string](d.cstDoc, d.cstDoc.Root(), "claude-allow"); err == nil {
		d.data.ClaudeAllow = v
		d.consumed["claude-allow"] = true
	}
	if v, err := document.GetFromContainer[[]string](d.cstDoc, d.cstDoc.Root(), "envrc-directives"); err == nil {
		d.data.EnvrcDirectives = v
		d.consumed["envrc-directives"] = true
	}
	if tableNode := d.cstDoc.FindTable("env"); tableNode != nil {
		d.data.Env = document.GetStringMapFromTable(tableNode)
		d.consumed["env"] = true
		document.MarkAllConsumed(tableNode, "env", d.consumed)
	}
	if tableNode := d.cstDoc.FindTableInContainer(d.cstDoc.Root(), "hooks"); tableNode != nil {
		d.consumed["hooks"] = true
		hooksVal := &Hooks{}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "create"); err == nil {
			hooksVal.Create = &v
			d.consumed["hooks.create"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "stop"); err == nil {
			hooksVal.Stop = &v
			d.consumed["hooks.stop"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "pre-merge"); err == nil {
			hooksVal.PreMerge = &v
			d.consumed["hooks.pre-merge"] = true
		}
		if v, err := document.GetFromContainer[bool](d.cstDoc, tableNode, "disallow-main-worktree"); err == nil {
			hooksVal.DisallowMainWorktree = &v
			d.consumed["hooks.disallow-main-worktree"] = true
		}
		d.data.Hooks = hooksVal
	} else {
		hooksVal := &Hooks{}
		found := false
		if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "create"); err == nil {
			hooksVal.Create = &v
			found = true
			d.consumed["create"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "stop"); err == nil {
			hooksVal.Stop = &v
			found = true
			d.consumed["stop"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "pre-merge"); err == nil {
			hooksVal.PreMerge = &v
			found = true
			d.consumed["pre-merge"] = true
		}
		if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "disallow-main-worktree"); err == nil {
			hooksVal.DisallowMainWorktree = &v
			found = true
			d.consumed["disallow-main-worktree"] = true
		}
		if found {
			d.data.Hooks = hooksVal
		}
	}

	return d, nil
}

func (d *SweatfileDocument) Data() *Sweatfile { return &d.data }

func (d *SweatfileDocument) Encode() ([]byte, error) {
	if d.data.SystemPrompt != nil {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "system-prompt", *d.data.SystemPrompt); err != nil {
			return nil, err
		}
	}
	if d.data.SystemPromptAppend != nil {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "system-prompt-append", *d.data.SystemPromptAppend); err != nil {
			return nil, err
		}
	}
	if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "git-excludes", d.data.GitSkipIndex); err != nil {
		return nil, err
	}
	if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "claude-allow", d.data.ClaudeAllow); err != nil {
		return nil, err
	}
	if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "envrc-directives", d.data.EnvrcDirectives); err != nil {
		return nil, err
	}
	if len(d.data.Env) > 0 {
		tableNode := d.cstDoc.EnsureTable("env")
		document.DeleteAllInContainer(tableNode)
		for k, v := range d.data.Env {
			if err := d.cstDoc.SetInContainer(tableNode, k, v); err != nil {
				return nil, err
			}
		}
	}
	if d.data.Hooks != nil {
		if tableNode := d.cstDoc.FindTableInContainer(d.cstDoc.Root(), "hooks"); tableNode != nil {
			if d.data.Hooks.Create != nil {
				if err := d.cstDoc.SetInContainer(tableNode, "create", *d.data.Hooks.Create); err != nil {
					return nil, err
				}
			}
			if d.data.Hooks.Stop != nil {
				if err := d.cstDoc.SetInContainer(tableNode, "stop", *d.data.Hooks.Stop); err != nil {
					return nil, err
				}
			}
			if d.data.Hooks.PreMerge != nil {
				if err := d.cstDoc.SetInContainer(tableNode, "pre-merge", *d.data.Hooks.PreMerge); err != nil {
					return nil, err
				}
			}
			if d.data.Hooks.DisallowMainWorktree != nil {
				if err := d.cstDoc.SetInContainer(tableNode, "disallow-main-worktree", *d.data.Hooks.DisallowMainWorktree); err != nil {
					return nil, err
				}
			}
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *SweatfileDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
